### ISSUE TITLE
Exception 리팩토링, 잘못된 HttpStatus 수정

### ISSUE THREAD

**Issue by YuSoeun** [I-Taxi/itaxi-server#169]
**Description**
- 잘못된 Exception Httpstatus 수정

**Todo**
- [x] 잘못된 Exception Httpstatus 수정
- [x] 인증 관련은 *`FORBIDDEN`* 으로 통일 (admin은 Unauthorized)
- [x] 삭제된거 찾으면 `NOT_FOUND` 로 통일
- [x] 파일 이름 일괄 수정
- [x]  겹치는 파일 삭제
- [x]  message 일괄 수정 (이름도)
