### ISSUE TITLE
한동대 전체, 양덕 전체 선택했을 때 전체 서치해서 주도록

### ISSUE THREAD

**Issue by YuSoeun** [I-Taxi/itaxi-server#212]
**Description**
- 한동대 전체, 양덕 전체 선택했을 때 전체 서치해서 주도록

**Todo**
- [x] 한동대 전체 선택했을 때 전체 서치해서 주도록
- [x] 양덕 전체 선택했을 때 전체 서치해서 주도록
- [x] postType 있는 경우
- [x] 한동대/양덕 전체가 모집 장소일 때 안 만들어지게
