### ISSUE TITLE
Member, Post API 코드 Refactoring

### ISSUE THREAD

**Issue by juyoungIt** [I-Taxi/itaxi-server#25]
**Description**
- 기존 Member관련 API의 Controller에서 HttpServletRequest를 사용하여 데이터를 넘겨받도록 구현하였으나, 이것이 flutter와 잘 호환이 되지않고, 최근에는 application/json type의 header가 많이 사용된다는 점을 확인하여 이 부분을 수정하여 기능적으로 제공하기로 결정함

**Todo**
- [x] Member API Parameter Passing 방식 변경 (HttpServletRequest => @RequestBody)
- [x] Post API Parameter Passing 방식 변경 (HttpServletRequest => @RequestBody (탑승내역, 탑승내역 상세조회))
- [x] 각 DTO 내에 입력된 Data Validation하는 로직 추가
- [x] 각 Service 단 코드에서 Exception 발생방식 변경

**ETC**
- 기타사항사항
