### ISSUE TITLE
Post, Notice API 부분 Refactoring

### ISSUE THREAD

**Issue by YuSoeun** [I-Taxi/itaxi-server#27]
**Description**
- 불필요한 코드 삭제
- Exception과 DTO 형식 통일

**Todo**
- [x] 불필요한 try-catch문 삭제
- [x] isDeleted checker 삭제 
- [x] entity 내 deleted 변수 삭제
- [x]  Return fail 대신 throw new Exception 보내기
- [x]  생성자에 불필요한 내용 있으면 따로 빼기
- [x]  Exception 추가할 사항 확인
- [x]  DTO 제대로 됐는지 확인

**Comment by YuSoeun** [comment]
1, 2, 3, 4 완료
