### ISSUE TITLE
Post API 내 status, owner 관련 세부 기능 추가

### ISSUE THREAD

**Issue by YuSoeun** [I-Taxi/itaxi-server#28]
**Description**
- Post API 내 status, owner 관련 세부 기능 추가

**Todo**
- [x] owner 여부 자동 설정 기능
- [x] post에 들어가는 status 자동업데이트 로직 설정
- [x] 방 나가기에 따른 owner 자동 변경
