### ISSUE TITLE
Post에 type 추가 및 검색 기능 추가

### ISSUE THREAD

**Issue by crystalYoo99** [I-Taxi/itaxi-server#31]
**Description**
- post에 type(카풀, 택시, ktx 구분용) 넣기. 
- 전체 0, 카풀 1, 택시 2

**Todo**
- [x] post에 type 넣기
- [x] post depId + deptTime 검색 기능 추가
- [x] post dstId + deptTime 검색 기능 추가
- [x] post depId + deptTime  + Type 검색 기능 추가
- [x] post dstId + deptTime + Type 검색 기능 추가
- [x] post depId + dstId + deptTime + Type 검색 기능 추가

**ETC**
- 기타사항 없음

**Comment by crystalYoo99** [comment]
depId, dstId, deptTime, postType 으로 검색가능하게 구현완료하였음.
여기에서 deptTime은 required true이므로 반드시 파라미터로 전달받아야 함.
그리고 나머지 depId, dstId, postType의 경우 파라미터를 아예 넘겨주지 않아도 괜찮고, null로 넘겨주더라도 정상적으로 동작하도록 구현하였음.
