### ISSUE TITLE
Notice API viewCnt 증가 기능 추가

### ISSUE THREAD

**Issue by YuSoeun** [I-Taxi/itaxi-server#41]
**Description**
- Notice API viewCnt 증가 기능 추가
- transactional 어노테이션 추가
- postType variable 추가

**Todo**
- [x] Notice API viewCnt 증가 기능 추가
- [x] transactional 어노테이션 추가
- [x] postType variable 추가
