### ISSUE TITLE
Post/Notice 버그 수정

### ISSUE THREAD

**Issue by YuSoeun** [I-Taxi/itaxi-server#57]
**Description**
- Notice 목록 시간 역순으로 response에 담도록 함.
- Post join 같은 멤버가 2번 이상 호출했을 때 Exception이 아닌 post 정보 반환할 수 있도록 함.
- post의 luggage 항목 제거

**Todo**
- [x] Notice 목록 시간 역순으로 response에 담기도록 바꾸기.
- [x] Post join 같은 멤버가 2번 이상 호출했을 때 Exception이 아닌 post 정보 반환할 수 있도록 하기.
- [ ] post의 luggage 항목 제거
