### ISSUE TITLE
Post 관련 CRUD API 구현

### ISSUE THREAD

**Issue by juyoungIt** [I-Taxi/itaxi-server#6]
## Description
- 모집글(Post) 관련 API에서 기본적인 CRUD를 지원하는 API를 개발합니다.

## Todo
- [x] (C) 방 만들기
- [x] (C) 방 입장
- [x] (R) 모든 게시글 불러오기
- [x] (R) 탑승 내역 조회
- [x] (R) 탑승 내역 상세조회
- [x] (U) 방 나가기
