### ISSUE TITLE
Place 관련 CRUD API 구현

### ISSUE THREAD

**Issue by crystalYoo99** [I-Taxi/itaxi-server#8]
**Description**
Place에 관련된 CRUD API를 구현한다.

**Todo**
제작해야 할 API 목록
- [x] Place Create (POST)
- [x] Place Read All (cnt 순서대로) (GET) 
- [x] Place Update (PUT)
- [x] Place Update Count (PUT)
- [x] Place Delete (DELETE)
